services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - data_volumes:/var/lib/postgresql
volumes:
  data_volumes:
